import sqlalchemy.exc

# Using https://postgrest.org/en/stable/references/errors.html
# A good number of these exceptions should hard break if they occur, so have been commented out to break the lookup
pgcode_lookups = {
    '02000': 404,  # (!) real value is "<class 'psycopg2.errors.NoData'>"
    # '02001': 500,  # (!) real value is "<class 'psycopg2.errors.NoAdditionalDynamicResultSetsReturned'>"
    # '03000': 500,  # (!) real value is "<class 'psycopg2.errors.SqlStatementNotYetComplete'>"
    # '08000': 503,  # (!) real value is "<class 'psycopg2.errors.ConnectionException'>"
    # '08001': 503,  # (!) real value is "<class 'psycopg2.errors.SqlclientUnableToEstablishSqlconnection'>"
    # '08003': 503,  # (!) real value is "<class 'psycopg2.errors.ConnectionDoesNotExist'>"
    # '08004': 503,  # (!) real value is "<class 'psycopg2.errors.SqlserverRejectedEstablishmentOfSqlconnection'>"
    # '08006': 503,  # (!) real value is "<class 'psycopg2.errors.ConnectionFailure'>"
    # '08007': 503,  # (!) real value is "<class 'psycopg2.errors.TransactionResolutionUnknown'>"
    # '08P01': 503,  # (!) real value is "<class 'psycopg2.errors.ProtocolViolation'>"
    # '09000': 500,  # (!) real value is "<class 'psycopg2.errors.TriggeredActionException'>"
    '0A000': 500,  # (!) real value is "<class 'psycopg2.errors.FeatureNotSupported'>"
    # '0B000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTransactionInitiation'>"
    # '0F000': 403,  # (!) real value is "<class 'psycopg2.errors.LocatorException'>"
    # '0F001': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidLocatorSpecification'>"
    # '0L000': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidGrantor'>"
    # '0LP01': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidGrantOperation'>"
    # '0P000': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidRoleSpecification'>"
    # '0Z000': 500,  # (!) real value is "<class 'psycopg2.errors.DiagnosticsException'>"
    # '0Z002': 500,  # (!) real value is "<class 'psycopg2.errors.StackedDiagnosticsAccessedWithoutActiveHandler'>"
    # '20000': 500,  # (!) real value is "<class 'psycopg2.errors.CaseNotFound'>"
    # '21000': 500,  # (!) real value is "<class 'psycopg2.errors.CardinalityViolation'>"
    # '22000': 500,  # (!) real value is "<class 'psycopg2.errors.DataException'>"
    # '22001': 500,  # (!) real value is "<class 'psycopg2.errors.StringDataRightTruncation'>"
    # '22002': 500,  # (!) real value is "<class 'psycopg2.errors.NullValueNoIndicatorParameter'>"
    # '22003': 500,  # (!) real value is "<class 'psycopg2.errors.NumericValueOutOfRange'>"
    # '22004': 500,  # (!) real value is "<class 'psycopg2.errors.NullValueNotAllowed'>"
    # '22005': 500,  # (!) real value is "<class 'psycopg2.errors.ErrorInAssignment'>"
    # '22007': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidDatetimeFormat'>"
    # '22008': 500,  # (!) real value is "<class 'psycopg2.errors.DatetimeFieldOverflow'>"
    # '22009': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTimeZoneDisplacementValue'>"
    # '2200B': 500,  # (!) real value is "<class 'psycopg2.errors.EscapeCharacterConflict'>"
    # '2200C': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidUseOfEscapeCharacter'>"
    # '2200D': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidEscapeOctet'>"
    # '2200F': 500,  # (!) real value is "<class 'psycopg2.errors.ZeroLengthCharacterString'>"
    # '2200G': 500,  # (!) real value is "<class 'psycopg2.errors.MostSpecificTypeMismatch'>"
    # '2200H': 500,  # (!) real value is "<class 'psycopg2.errors.SequenceGeneratorLimitExceeded'>"
    # '2200L': 500,  # (!) real value is "<class 'psycopg2.errors.NotAnXmlDocument'>"
    # '2200M': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidXmlDocument'>"
    # '2200N': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidXmlContent'>"
    # '2200S': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidXmlComment'>"
    # '2200T': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidXmlProcessingInstruction'>"
    # '22010': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidIndicatorParameterValue'>"
    '22011': 422,  # (!) real value is "<class 'psycopg2.errors.SubstringError'>"
    '22012': 422,  # (!) real value is "<class 'psycopg2.errors.DivisionByZero'>"
    # '22013': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidPrecedingOrFollowingSize'>"
    # '22014': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForNtileFunction'>"
    # '22015': 500,  # (!) real value is "<class 'psycopg2.errors.IntervalFieldOverflow'>"
    # '22016': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForNthValueFunction'>"
    # '22018': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidCharacterValueForCast'>"
    '22019': 422,  # (!) real value is "<class 'psycopg2.errors.InvalidEscapeCharacter'>"
    # '2201B': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidRegularExpression'>"
    # '2201E': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForLogarithm'>"
    # '2201F': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForPowerFunction'>"
    # '2201G': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForWidthBucketFunction'>"
    # '2201W': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidRowCountInLimitClause'>"
    # '2201X': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidRowCountInResultOffsetClause'>"
    # '22021': 500,  # (!) real value is "<class 'psycopg2.errors.CharacterNotInRepertoire'>"
    # '22022': 500,  # (!) real value is "<class 'psycopg2.errors.IndicatorOverflow'>"
    # '22023': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidParameterValue'>"
    # '22024': 500,  # (!) real value is "<class 'psycopg2.errors.UnterminatedCString'>"
    # '22025': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidEscapeSequence'>"
    # '22026': 500,  # (!) real value is "<class 'psycopg2.errors.StringDataLengthMismatch'>"
    # '22027': 500,  # (!) real value is "<class 'psycopg2.errors.TrimError'>"
    # '2202E': 500,  # (!) real value is "<class 'psycopg2.errors.ArraySubscriptError'>"
    # '2202G': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTablesampleRepeat'>"
    # '2202H': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTablesampleArgument'>"
    '22030': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateJsonObjectKeyValue'>"
    # '22031': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidArgumentForSqlJsonDatetimeFunction'>"
    # '22032': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidJsonText'>"
    # '22033': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSqlJsonSubscript'>"
    # '22034': 500,  # (!) real value is "<class 'psycopg2.errors.MoreThanOneSqlJsonItem'>"
    # '22035': 500,  # (!) real value is "<class 'psycopg2.errors.NoSqlJsonItem'>"
    # '22036': 500,  # (!) real value is "<class 'psycopg2.errors.NonNumericSqlJsonItem'>"
    '22037': 422,  # (!) real value is "<class 'psycopg2.errors.NonUniqueKeysInAJsonObject'>"
    # '22038': 500,  # (!) real value is "<class 'psycopg2.errors.SingletonSqlJsonItemRequired'>"
    # '22039': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonArrayNotFound'>"
    # '2203A': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonMemberNotFound'>"
    # '2203B': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonNumberNotFound'>"
    # '2203C': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonObjectNotFound'>"
    # '2203D': 500,  # (!) real value is "<class 'psycopg2.errors.TooManyJsonArrayElements'>"
    # '2203E': 500,  # (!) real value is "<class 'psycopg2.errors.TooManyJsonObjectMembers'>"
    # '2203F': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonScalarRequired'>"
    # '2203G': 500,  # (!) real value is "<class 'psycopg2.errors.SqlJsonItemCannotBeCastToTargetType'>"
    # '22P01': 500,  # (!) real value is "<class 'psycopg2.errors.FloatingPointException'>"
    # '22P02': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTextRepresentation'>"
    # '22P03': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidBinaryRepresentation'>"
    # '22P04': 500,  # (!) real value is "<class 'psycopg2.errors.BadCopyFileFormat'>"
    # '22P05': 500,  # (!) real value is "<class 'psycopg2.errors.UntranslatableCharacter'>"
    # '22P06': 500,  # (!) real value is "<class 'psycopg2.errors.NonstandardUseOfEscapeCharacter'>"
    # '23000': 500,  # (!) real value is "<class 'psycopg2.errors.IntegrityConstraintViolation'>"
    # '23001': 500,  # (!) real value is "<class 'psycopg2.errors.RestrictViolation'>"
    # '23502': 500,  # (!) real value is "<class 'psycopg2.errors.NotNullViolation'>"
    '23503': 404,  # (!) real value is "<class 'psycopg2.errors.ForeignKeyViolation'>"
    '23505': 409,  # (!) real value is "<class 'psycopg2.errors.UniqueViolation'>"
    '23514': 500,  # (!) real value is "<class 'psycopg2.errors.CheckViolation'>"
    '23P01': 500,  # (!) real value is "<class 'psycopg2.errors.ExclusionViolation'>"
    '24000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidCursorState'>"
    # '25000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTransactionState'>"
    # '25001': 500,  # (!) real value is "<class 'psycopg2.errors.ActiveSqlTransaction'>"
    # '25002': 500,  # (!) real value is "<class 'psycopg2.errors.BranchTransactionAlreadyActive'>"
    # '25003': 500,  # (!) real value is "<class 'psycopg2.errors.InappropriateAccessModeForBranchTransaction'>"
    # '25004': 500,  # (!) real value is "<class 'psycopg2.errors.InappropriateIsolationLevelForBranchTransaction'>"
    # '25005': 500,  # (!) real value is "<class 'psycopg2.errors.NoActiveSqlTransactionForBranchTransaction'>"
    # '25006': 500,  # (!) real value is "<class 'psycopg2.errors.ReadOnlySqlTransaction'>"
    # '25007': 500,  # (!) real value is "<class 'psycopg2.errors.SchemaAndDataStatementMixingNotSupported'>"
    # '25008': 500,  # (!) real value is "<class 'psycopg2.errors.HeldCursorRequiresSameIsolationLevel'>"
    # '25P01': 500,  # (!) real value is "<class 'psycopg2.errors.NoActiveSqlTransaction'>"
    # '25P02': 500,  # (!) real value is "<class 'psycopg2.errors.InFailedSqlTransaction'>"
    # '25P03': 500,  # (!) real value is "<class 'psycopg2.errors.IdleInTransactionSessionTimeout'>"
    # '26000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSqlStatementName'>"
    # '27000': 500,  # (!) real value is "<class 'psycopg2.errors.TriggeredDataChangeViolation'>"
    '28000': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidAuthorizationSpecification'>"
    '28P01': 403,  # (!) real value is "<class 'psycopg2.errors.InvalidPassword'>"
    '2B000': 403,  # (!) real value is "<class 'psycopg2.errors.DependentPrivilegeDescriptorsStillExist'>"
    '2BP01': 403,  # (!) real value is "<class 'psycopg2.errors.DependentObjectsStillExist'>"
    # '2D000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTransactionTermination'>"
    # '2F000': 500,  # (!) real value is "<class 'psycopg2.errors.SqlRoutineException'>"
    # '2F002': 500,  # (!) real value is "<class 'psycopg2.errors.ModifyingSqlDataNotPermitted'>"
    # '2F003': 500,  # (!) real value is "<class 'psycopg2.errors.ProhibitedSqlStatementAttempted'>"
    # '2F004': 500,  # (!) real value is "<class 'psycopg2.errors.ReadingSqlDataNotPermitted'>"
    # '2F005': 500,  # (!) real value is "<class 'psycopg2.errors.FunctionExecutedNoReturnStatement'>"
    # '34000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidCursorName'>"
    # '38000': 500,  # (!) real value is "<class 'psycopg2.errors.ExternalRoutineException'>"
    # '38001': 500,  # (!) real value is "<class 'psycopg2.errors.ContainingSqlNotPermitted'>"
    # '38002': 500,  # (!) real value is "<class 'psycopg2.errors.ModifyingSqlDataNotPermittedExt'>"
    # '38003': 500,  # (!) real value is "<class 'psycopg2.errors.ProhibitedSqlStatementAttemptedExt'>"
    # '38004': 500,  # (!) real value is "<class 'psycopg2.errors.ReadingSqlDataNotPermittedExt'>"
    # '39000': 500,  # (!) real value is "<class 'psycopg2.errors.ExternalRoutineInvocationException'>"
    # '39001': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSqlstateReturned'>"
    '39004': 422,  # (!) real value is "<class 'psycopg2.errors.NullValueNotAllowedExt'>"
    # '39P01': 500,  # (!) real value is "<class 'psycopg2.errors.TriggerProtocolViolated'>"
    # '39P02': 500,  # (!) real value is "<class 'psycopg2.errors.SrfProtocolViolated'>"
    # '39P03': 500,  # (!) real value is "<class 'psycopg2.errors.EventTriggerProtocolViolated'>"
    # '3B000': 503,  # (!) real value is "<class 'psycopg2.errors.SavepointException'>"
    # '3B001': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSavepointSpecification'>"
    # '3D000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidCatalogName'>"
    # '3F000': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSchemaName'>"
    '40000': 503,  # (!) real value is "<class 'psycopg2.errors.TransactionRollback'>"
    # '40001': 500,  # (!) real value is "<class 'psycopg2.errors.SerializationFailure'>"
    # '40002': 500,  # (!) real value is "<class 'psycopg2.errors.TransactionIntegrityConstraintViolation'>"
    # '40003': 500,  # (!) real value is "<class 'psycopg2.errors.StatementCompletionUnknown'>"
    '40P01': 500,  # (!) real value is "<class 'psycopg2.errors.DeadlockDetected'>"
    # '42000': 500,  # (!) real value is "<class 'psycopg2.errors.SyntaxErrorOrAccessRuleViolation'>"
    '42501': 403,  # (!) real value is "<class 'psycopg2.errors.InsufficientPrivilege'>"
    '42601': 500,  # (!) real value is "<class 'psycopg2.errors.SyntaxError'>"
    # '42602': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidName'>"
    # '42611': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidColumnDefinition'>"
    '42622': 500,  # (!) real value is "<class 'psycopg2.errors.NameTooLong'>"
    # '42701': 500,  # (!) real value is "<class 'psycopg2.errors.DuplicateColumn'>"
    # '42702': 500,  # (!) real value is "<class 'psycopg2.errors.AmbiguousColumn'>"
    # '42703': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedColumn'>"
    '42704': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedObject'>"
    '42710': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateObject'>"
    '42712': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateAlias'>"
    '42723': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateFunction'>"
    '42725': 500,  # (!) real value is "<class 'psycopg2.errors.AmbiguousFunction'>"
    # '42803': 500,  # (!) real value is "<class 'psycopg2.errors.GroupingError'>"
    '42804': 422,  # (!) real value is "<class 'psycopg2.errors.DatatypeMismatch'>"
    # '42809': 500,  # (!) real value is "<class 'psycopg2.errors.WrongObjectType'>"
    '42830': 422,  # (!) real value is "<class 'psycopg2.errors.InvalidForeignKey'>"
    # '42846': 500,  # (!) real value is "<class 'psycopg2.errors.CannotCoerce'>"
    # '42883': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedFunction'>"
    # '428C9': 500,  # (!) real value is "<class 'psycopg2.errors.GeneratedAlways'>"
    # '42939': 500,  # (!) real value is "<class 'psycopg2.errors.ReservedName'>"
    # '42P01': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedTable'>"
    # '42P02': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedParameter'>"
    # '42P03': 500,  # (!) real value is "<class 'psycopg2.errors.DuplicateCursor'>"
    '42P04': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateDatabase'>"
    '42P05': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicatePreparedStatement'>"
    '42P06': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateSchema'>"
    '42P07': 409,  # (!) real value is "<class 'psycopg2.errors.DuplicateTable'>"
    # '42P08': 500,  # (!) real value is "<class 'psycopg2.errors.AmbiguousParameter'>"
    # '42P09': 500,  # (!) real value is "<class 'psycopg2.errors.AmbiguousAlias'>"
    '42P10': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidColumnReference'>"
    # '42P11': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidCursorDefinition'>"
    '42P12': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidDatabaseDefinition'>"
    # '42P13': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidFunctionDefinition'>"
    '42P14': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidPreparedStatementDefinition'>"
    '42P15': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidSchemaDefinition'>"
    '42P16': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidTableDefinition'>"
    '42P17': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidObjectDefinition'>"
    # '42P18': 500,  # (!) real value is "<class 'psycopg2.errors.IndeterminateDatatype'>"
    '42P19': 500,  # (!) real value is "<class 'psycopg2.errors.InvalidRecursion'>"
    # '42P20': 500,  # (!) real value is "<class 'psycopg2.errors.WindowingError'>"
    # '42P21': 500,  # (!) real value is "<class 'psycopg2.errors.CollationMismatch'>"
    # '42P22': 500,  # (!) real value is "<class 'psycopg2.errors.IndeterminateCollation'>"
    '44000': 500,  # (!) real value is "<class 'psycopg2.errors.WithCheckOptionViolation'>"
    '53000': 503,  # (!) real value is "<class 'psycopg2.errors.InsufficientResources'>"
    # '53100': 503,  # (!) real value is "<class 'psycopg2.errors.DiskFull'>"
    '53200': 503,  # (!) real value is "<class 'psycopg2.errors.OutOfMemory'>"
    # '53300': 503,  # (!) real value is "<class 'psycopg2.errors.TooManyConnections'>"
    # '53400': 503,  # (!) real value is "<class 'psycopg2.errors.ConfigurationLimitExceeded'>"
    # '54000': 513,  # (!) real value is "<class 'psycopg2.errors.ProgramLimitExceeded'>"
    # '54001': 513,  # (!) real value is "<class 'psycopg2.errors.StatementTooComplex'>"
    # '54011': 513,  # (!) real value is "<class 'psycopg2.errors.TooManyColumns'>"
    '54023': 513,  # (!) real value is "<class 'psycopg2.errors.TooManyArguments'>"
    # '55000': 500,  # (!) real value is "<class 'psycopg2.errors.ObjectNotInPrerequisiteState'>"
    # '55006': 500,  # (!) real value is "<class 'psycopg2.errors.ObjectInUse'>"
    # '55P02': 500,  # (!) real value is "<class 'psycopg2.errors.CantChangeRuntimeParam'>"
    # '55P03': 500,  # (!) real value is "<class 'psycopg2.errors.LockNotAvailable'>"
    # '55P04': 500,  # (!) real value is "<class 'psycopg2.errors.UnsafeNewEnumValueUsage'>"
    # '57000': 500,  # (!) real value is "<class 'psycopg2.errors.OperatorIntervention'>"
    # '57014': 500,  # (!) real value is "<class 'psycopg2.errors.QueryCanceled'>"
    '57P01': 500,  # (!) real value is "<class 'psycopg2.errors.AdminShutdown'>"
    # '57P02': 500,  # (!) real value is "<class 'psycopg2.errors.CrashShutdown'>"
    # '57P03': 500,  # (!) real value is "<class 'psycopg2.errors.CannotConnectNow'>"
    '57P04': 500,  # (!) real value is "<class 'psycopg2.errors.DatabaseDropped'>"
    '57P05': 500,  # (!) real value is "<class 'psycopg2.errors.IdleSessionTimeout'>"
    '58000': 500,  # (!) real value is "<class 'psycopg2.errors.SystemError'>"
    # '58030': 500,  # (!) real value is "<class 'psycopg2.errors.IoError'>"
    # '58P01': 500,  # (!) real value is "<class 'psycopg2.errors.UndefinedFile'>"
    '58P02': 500,  # (!) real value is "<class 'psycopg2.errors.DuplicateFile'>"
    # '72000': 500,  # (!) real value is "<class 'psycopg2.errors.SnapshotTooOld'>"
    'F0000': 500,  # (!) real value is "<class 'psycopg2.errors.ConfigFileError'>"
    # 'F0001': 500,  # (!) real value is "<class 'psycopg2.errors.LockFileExists'>"
    'HV000': 500,  # (!) real value is "<class 'psycopg2.errors.FdwError'>"
    'HV001': 500,  # (!) real value is "<class 'psycopg2.errors.FdwOutOfMemory'>"
    # 'HV002': 500,  # (!) real value is "<class 'psycopg2.errors.FdwDynamicParameterValueNeeded'>"
    'HV004': 422,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidDataType'>"
    # 'HV005': 404,  # (!) real value is "<class 'psycopg2.errors.FdwColumnNameNotFound'>"
    # 'HV006': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidDataTypeDescriptors'>"
    # 'HV007': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidColumnName'>"
    # 'HV008': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidColumnNumber'>"
    # 'HV009': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidUseOfNullPointer'>"
    # 'HV00A': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidStringFormat'>"
    # 'HV00B': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidHandle'>"
    # 'HV00C': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidOptionIndex'>"
    # 'HV00D': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidOptionName'>"
    # 'HV00J': 500,  # (!) real value is "<class 'psycopg2.errors.FdwOptionNameNotFound'>"
    # 'HV00K': 500,  # (!) real value is "<class 'psycopg2.errors.FdwReplyHandle'>"
    # 'HV00L': 500,  # (!) real value is "<class 'psycopg2.errors.FdwUnableToCreateExecution'>"
    # 'HV00M': 500,  # (!) real value is "<class 'psycopg2.errors.FdwUnableToCreateReply'>"
    # 'HV00N': 500,  # (!) real value is "<class 'psycopg2.errors.FdwUnableToEstablishConnection'>"
    # 'HV00P': 500,  # (!) real value is "<class 'psycopg2.errors.FdwNoSchemas'>"
    'HV00Q': 404,  # (!) real value is "<class 'psycopg2.errors.FdwSchemaNotFound'>"
    # 'HV00R': 404,  # (!) real value is "<class 'psycopg2.errors.FdwTableNotFound'>"
    # 'HV010': 500,  # (!) real value is "<class 'psycopg2.errors.FdwFunctionSequenceError'>"
    # 'HV014': 500,  # (!) real value is "<class 'psycopg2.errors.FdwTooManyHandles'>"
    # 'HV021': 500,  # (!) real value is "<class 'psycopg2.errors.FdwInconsistentDescriptorInformation'>"
    # 'HV024': 422,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidAttributeValue'>"
    # 'HV090': 422,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidStringLengthOrBufferLength'>"
    # 'HV091': 422,  # (!) real value is "<class 'psycopg2.errors.FdwInvalidDescriptorFieldIdentifier'>"
    # 'P0000': 500,  # (!) real value is "<class 'psycopg2.errors.PlpgsqlError'>"
    'P0001': 400,  # (!) real value is "<class 'psycopg2.errors.RaiseException'>"
    # 'P0002': 404,  # (!) real value is "<class 'psycopg2.errors.NoDataFound'>"
    # 'P0003': 500,  # (!) real value is "<class 'psycopg2.errors.TooManyRows'>"
    # 'P0004': 500,  # (!) real value is "<class 'psycopg2.errors.AssertFailure'>"
    'XX000': 500,  # (!) real value is "<class 'psycopg2.errors.InternalError_'>"
    # 'XX001': 500,  # (!) real value is "<class 'psycopg2.errors.DataCorrupted'>"
    # 'XX002': 500,  # (!) real value is "<class 'psycopg2.errors.IndexCorrupted'>"
}

sqlalchemy_error_lookup = {
    'NoResultFound': 404,
    'IntegrityError': 500,
    # 'InvalidRequestError': 500,
}
